### ISSUE TITLE
create navbar

### ISSUE THREAD

**Issue by EdilAbe** [vanlyfe/capstone#7]
As a user, I want to use a navbar to navigate to the pages on the website.

DESCRIPTION:
A static navigation bar at the top of every app page that covers the width of the page

A/C:

- [x] Should be blue in color
- [x] Should have a profile avatar on the far right that links to a user profile 
- [x] Should have an "Add listing" button that navigates to a form page to enable a user add a listing
- [x] Should have the app logo on the far left that links to the home page

DoD:

- [x]  All acceptance criteria are met

**Comment by thismustbevernon** [comment]
updated responsive navbar
